### ISSUE TITLE
HMMsearch.extractIds.rb incompatible with HMMER 3.1b2

### ISSUE THREAD

**Issue by lhor** [lmrodriguezr/enveomics#13]
HMMsearch.extractIds.rb doesn't seem to be working with HMMer 3.1b2 (latest). I get the following error:
Unable to parse seemingly malformed list of hits in line 19: (RuntimeError)

**Comment by lmrodriguezr** [comment]
@lhor Could you please make a [gist](https://gist.github.com/) with the input file?
