### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by adalgarno** [lmrodriguezr/enveomics#20]
I've had trouble running both aai.rb and aai-matrix.bash and continually receive the following error for both:

enveomics/Scripts/aai.rb:23: syntax error, unexpected tSYMBEG, expecting kDO or '{' or '('
o = {bits:0, id:20, len:0, hits:50, q:fa...
          ^

Any recommendations on how to fix this? Thanks

**Comment by lmrodriguezr** [comment]
What version of Ruby are you using? This error looks like no support for 1.9+ key style.

**Comment by adalgarno** [comment]
I am using Ruby 2.3.1.

**Comment by lmrodriguezr** [comment]
It might be a problem with some lingering all ruby in the environment. Please send the output of the following commands:
````bash
which ruby
ruby --version
ruby enveomics/Scripts/aai.rb
./enveomics/Scripts/aai.rb
````

**Comment by adalgarno** [comment]
Here is the output you requested:


[dalgarno@e070 dir_2071749]$ which ruby

/usr/bin/ruby

[dalgarno@e070 dir_2071749]$ ruby --version

ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

[dalgarno@e070 dir_2071749]$ ruby enveomics/Scripts/aai.rb

enveomics/Scripts/aai.rb:23: syntax error, unexpected tSYMBEG, expecting
kDO or '{' or '('

o = {bits:0, id:20, len:0, hits:50, q:fa...

          ^

[dalgarno@e070 dir_2071749]$ ./enveomics/Scripts/aai.rb

./enveomics/Scripts/aai.rb:23: syntax error, unexpected tSYMBEG, expecting
kDO or '{' or '('

o = {bits:0, id:20, len:0, hits:50, q:fa...

          ^

This is output from an interactive session on a submit node linked to
HTCondor (high-throughput computing).  The Ruby I thought we installed
was ruby-2.3.1, as this was the version we untar-ed.  Any insight you can
offer on fixing this would be greatly appreciated as I have limited
experience with Ruby and the HTCondor system we have been using.  Thanks,

Audrey

**Comment by lmrodriguezr** [comment]
Hello @adalgarno 
It looks like you'll need to contact your system administrator to install a more recent version of Ruby. Unfortunately, the enveomics scripts don't offer support for Ruby pre-1.9. Alternatively, if you have a local version of a recent Ruby, you can add it to the `PATH` in front of `/usr/bin`.
