### ISSUE TITLE
Mulithreading aai

### ISSUE THREAD

**Issue by sbridel** [lmrodriguezr/enveomics#24]
Well, i'm using aai-matrix.bash but THR=2 is never used in the script
I have modified aai-matrix.bash to 
```
AAI=$(${aai_rb} -1 "$i" -2 "$j" -S "$OUT.db" -t "$THR"\
		--no-save-rbm --auto)
```
And then i launched aai-matrix.bash but only one CPU is used by the script
 
What should I do to use aai.rb with multithreading?

**Comment by lmrodriguezr** [comment]
Hello @sbridel 
You're right, I'll add your patch to the repo, thanks!

`aai.rb` passes the value of `-t` directly to BLAST, but BLAST is not great at multithreading. I usually get a maximum of 2X speed-up (even with large numbers of threads), so I wouldn't be surprised if you don't see any difference. Note that the `aai.rb` script itself will only use 1 CPU, it's the child BLAST process that may use more than one.

A much better alternative is to parallelize the matrix process itself, which can be done in [MiGA](http://code.microbial-genomes.com/miga), but that requires additional setup. I'll close the issue after I include your change, but please feel free to reopen it if you think there is something wrong here.

**Comment by sbridel** [comment]
Unfortunately i can't read MiGA documentation. I see only the titles on the doc.

I was wondering how blast is call within aai.rb. 
Then, I wonder how to add mpiBLAST (http://www.mpiblast.org/) in aai.rb to do the job
